//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCS.DTV.RZC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtvGame
    {
        public int GameNumber { get; set; }
        public string DtvTricodeHome { get; set; }
        public string DtvTricodeAway { get; set; }
        public string GameDate { get; set; }
        public string Channel { get; set; }
        public string Network { get; set; }
        public string StartTime { get; set; }
    }
}
