//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCS.DTV.RZC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameRusher
    {
        public Nullable<int> GameKey { get; set; }
        public string Tricode { get; set; }
        public string JerseyNumber { get; set; }
        public string PlayerName { get; set; }
        public Nullable<int> Attempts { get; set; }
        public Nullable<int> Yards { get; set; }
        public string Average { get; set; }
        public Nullable<int> Long { get; set; }
        public Nullable<int> Touchdowns { get; set; }
        public Nullable<int> LongestTouchdownRush { get; set; }
        public string PlayerID { get; set; }
        public string StatString { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Position { get; set; }
        public int Id { get; set; }
    }
}
