//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCS.DTV.RZC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameLocation
    {
        public string Tri { get; set; }
        public string Location { get; set; }
        public string Stadium { get; set; }
        public int Id { get; set; }
    }
}
